name = "Createmon"
author = "KrashD"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf99e1c7c8244c9f6cceea64bbf4255134d588f4c5df8be5d7f4889e9110db8a"

[versions]
forge = "47.2.4"
minecraft = "1.20.1"
