name = "Createmon"
author = "KrashD"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "769137ef8c13d967bfcd0c1ebd9cee4712be1b07cae6601861580f2df6e5d2d0"

[versions]
forge = "47.2.4"
minecraft = "1.20.1"
