name = "Createmon"
author = "KrashD"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18966c1bbf5f4ee9b48ea1abce77d014a48a571ae566e4dcb4b52d20cabeed10"

[versions]
forge = "47.2.4"
minecraft = "1.20.1"
